### PR TITLE
#9 Create login page database design ( users.sql )

### PR DESCRIPTION
**Pull request by saran-mani**
Table name : Users

Fields

Id - string Primary Key
username - unique
password - hash key encription
emailId-string
phone-string
joinDate - timestamp
modifiedDate - timestamp
primaryLocation - string
profileSettings - Json

### CODE REVIEW

**Comment by lingibelli** [comment]
@saran-mani , Hi Saran, Thank you for the pull request. I have a suggestion. Lets us have a common file as atthelocal_create_database.sql file  and atthelocal_update_database.sql which can have all our sql  statements to setup and update the database. When anyone of us run that sql file against our database, a new database with all the tables, constraints would be create or existing table would be updated with the new fields.

@nurav05 , Ramesh Anna, What is your opinion?

**Comment by lingibelli** [comment]
@saran-mani , Hi Saran, Please for next time lets have the feature name something like this "**feature/9-CreateUserDatabaseTable**".

By this way it would be easy for the review to understand its a "**feature**" and it is issue number "**9**" and it deals with "**User database Table Creation**" 

Thank you.

**Comment by lingibelli** [comment]
Sorry Saran, I just realised you created the feature as expected. I got confused with the  pull request title. Please disregard my earlier comment about the feature naming convention. Good job.

**Comment by saran-mani** [comment]
I made code change with atthelocal_create_database.sql file and atthelocal_update_database.sql 43676c9e6dd47483582821a5c490409d9d59616d

**Pull request closed without merging**
